spring:
  application:
    name: userdetails
  cloud:
    config:
      discovery: 
        enabled: true
      uri: http://localhost:8886,http://localhost:8887
---
spring:
  config:
    import: optional:configserver:http://localhost:8886
    